baseURL = 'https://olshansky.me/'
languageCode = 'en-us'
title = 'Holistic scientist'
theme = 'hugo-vitae'

[[menu.main]]
  name ="Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3
